dist: bionic

env:
  global:
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++

jobs:
  - arch: amd64
    env: TARGET=amd64
  - arch: ppc64le
    env: 
      - TARGET=ppc64le
      - BUILD=power
    addon:
      apt: maven
      
script:
  - arch
  - echo $CC
  - echo $TARGET
